In [1]:
from simplerl import Policy, MaxQPolicy, DQN, BasicExperienceBuffer, DiscreteRandomPolicy, compare_lists_of_np_arrays, unzip_experience_buffer
import torch.nn as nn
import torch

In [2]:
class LinearNet(nn.Module):
        def __init__(self):
            super().__init__()
            self.fc = nn.Linear(1, 2, bias=False)

        def forward(self, x):
            return self.fc(x)

net = LinearNet()

In [3]:
weights  = net.state_dict()
weights['fc.weight'] = torch.FloatTensor([[2.0],[-1.0]])
net.load_state_dict(weights)

assert torch.equal(net(torch.FloatTensor([[2]])), torch.FloatTensor([[ 4., -2.]]))

In [4]:
policy = MaxQPolicy(net, num_actions=2)

In [5]:
policy.calc_q_values(torch.FloatTensor([[0.44]]))

tensor([[ 0.8800, -0.4400]], grad_fn=<MmBackward0>)

In [6]:
agent = DQN(buffer=BasicExperienceBuffer(size=10, batch_size=2), gamma=0.9, epsilon=0.1, policy=policy)
import numpy as np

In [7]:
buffer = BasicExperienceBuffer(size=10, batch_size=2)
buffer.add(np.array([1.0]), 2, 3, np.array([4.0]))
buffer.add(np.array([1.0]), 2, 3, np.array([-2.0]))
buffer.add(np.array([1.0]), 2, 3, np.array([1.0]))


states, actions, rewards, next_states = unzip_experience_buffer(buffer)


In [8]:
out = agent.next_state_maxq_values(next_states=next_states)
torch.equal(out.float(), torch.FloatTensor([1,2,3]))

False

In [9]:
s_ = torch.from_numpy(np.stack(next_states)).float()
s_
# policy.net
# policy(s_)

tensor([[ 4.],
        [-2.],
        [ 1.]])

In [10]:
tensor = torch.from_numpy(np.stack(next_states))

In [11]:
ten=agent.policy.net(tensor.float())
ten

tensor([[ 8., -4.],
        [-4.,  2.],
        [ 2., -1.]], grad_fn=<MmBackward0>)

In [12]:
# agent.next_state_maxq_values(states)
ten.max(dim=1)

torch.return_types.max(
values=tensor([8., 2., 2.], grad_fn=<MaxBackward0>),
indices=tensor([0, 1, 0]))

In [13]:
import numpy as np
class LinearNet(nn.Module):
    """Dummy network"""
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(1, 2, bias=False)

    def forward(self, x):
        return self.fc(x)
net = LinearNet()
weights  = net.state_dict()
weights['fc.weight'] = torch.FloatTensor([[2.0],[-1.0]])
net.load_state_dict(weights)
policy = MaxQPolicy(net, num_actions=2)
# instantiate a DQN agent
buffer = BasicExperienceBuffer(size=10, batch_size=2)
dqn = DQN(buffer=buffer, gamma=0.9, epsilon=0.1, policy=policy)

buffer.add(np.array([1.0]), 2, 3, np.array([4.0]))
buffer.add(np.array([1.0]), 2, 3, np.array([-2.0]))
buffer.add(np.array([1.0]), 2, 3, np.array([1.0]))

states, actions, rewards, next_states = unzip_experience_buffer(buffer)
print(dqn.next_state_maxq_values(next_states).float())
torch.equal(dqn.next_state_maxq_values(next_states), torch.Tensor([8.0, 2.0, 2.0]))

        

tensor([8., 2., 2.])


False

In [14]:
s_ = torch.from_numpy(np.stack(next_states)).float()
q_values = policy.calc_q_values(s_)
max_q_values = q_values.max(dim=1)

In [15]:
max_q_values.values

tensor([8., 2., 2.], grad_fn=<MaxBackward0>)